### ISSUE TITLE
WP 3.5.2 A Begin developing generation 3 Butler capability

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lsst-ir-fusion#30]

**Comment by raphaelshirley** [comment]
We have started development of the gen 3 pipeline. There are significant changes, the gen 3 Butler is still under development. The introduction tutorial to the gen 3 pipelines is available here:

https://pipelines.lsst.io/v/weekly/getting-started/index.html

The early test script to run the gen 3 pipeline with VISTA data on a test patch is available here:

https://github.com/lsst-uk/lsst-ir-fusion/blob/master/dmu4/dmu4_Example/test_patch_gen3.sh

The next steps are to integrate the HSC images, fix some issues with the reference catalogues, and update the skymap patch labelling.
