### ISSUE TITLE
WP 3.5.2 C Compare scientific results obtained with previous HSC-VISTA forced photometry.

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lsst-ir-fusion#32]

**Comment by raphaelshirley** [comment]
We have compared photometric and astrometric performance to the previous SExtractor catalogues. An example comparison on the SXDS field is here*:

https://github.com/lsst-uk/lsst-ir-fusion/blob/master/dmu5/dmu5_VIDEO/2.1_Diagnostics_P2021.1.ipynb

Spectroscopic samples have successfully had SED fits performed with the CIGALE code. We are now moving on to testing photometric redshift performance.

* Large notebook can be slow or fail to load on the GitHub website
