### ISSUE TITLE
Drafting and completing the WP3.5 (UKD-UKD-05) work plan 

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lsst-ir-fusion#45]

**Comment by tms-epcc** [comment]
Expecting IPC team to contact in w/b 22/NOV with workplan form

**Comment by tms-epcc** [comment]
Workplan form should now be completed in cooperation with recipient groups. The Work Plan form is available at: https://forms.gle/8QTHbZisz8DxTutm7

**Comment by tms-epcc** [comment]
04/FEB/22
- according to AprajitaV, this requires different workplan forms
- AprajitaV will confirm when forms are ready and reporting can start

**Comment by tms-epcc** [comment]
25/MAR/22
- awaiting instructions from AprajitaV

**Comment by tms-epcc** [comment]
06/MAY/22
- Manda met Steve Ridgeway, AprajitaV, and KnutO to  discuss contribution.
- Manda will now complete the workplan form and update the profile  explorer. If necessary, Manada to contact AprajitaV for write privileges to 
    the explorer.

**Comment by tms-epcc** [comment]
27/MAY/22
- workplan has been submitted
- profile explorer not modified, waiting for feedback on the workplan

**Comment by tms-epcc** [comment]
26/JUL/22
- at meeting with @tms-epcc, @aprajita  said will remind Steve Ridgeway and Steve Marghein to do the IPC 
  check on S5

**Comment by aprajita** [comment]
is done will send approval shortly

**Comment by tms-epcc** [comment]
- 07/SEP/22 : Contribution IPC (Steve Marghein) and Receipient reviewer (Knut Olsen) approved workplan with minor modifications i.e.  they  requested links to rep and notebooks.
- 12/SEP/22 : @raphaelshirley provided these.
